name: "Build and Deploy"
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn
        working-directory: ./aofiee.dev/theme/_mytheme/site/
      - name: Build
        run: yarn build
        working-directory: ./aofiee.dev/theme/_mytheme/site/
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: ./aofiee.dev/theme/_mytheme/site/public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: ./aofiee.dev/theme/_mytheme/site/public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_HOSTING }}
          PROJECT_PATH: ./aofiee.dev/theme/_mytheme/site/